### ISSUE TITLE
Confirmation not working

### ISSUE THREAD

**Issue by lasfter** [lasfter/Calendr#6]
User receives confirmation in email, but is told the token is invalid when they click it

**Comment by jayelle** [comment]
works perfectly now \o/ can't upload to the heroku master atm but i cloned this and uploaded it to a new one and it works fine. issue was with migration files and the mailing stuff in production.rb basically

**Comment by guanhuay** [comment]
just upload it as a new branch to github and we can merge it on Friday tommorrow.

**Comment by jayelle** [comment]
i just pushed it to master here on github so it's fine haaha there weren't really any conflicts

**Comment by jayelle** [comment]
it's just not on heroku
