### ISSUE TITLE
Display sign up errors more prettily

### ISSUE THREAD

**Issue by lasfter** [lasfter/Calendr#8]
Right now if I do something wrong on the user sign up page, like trying to use an email that already exists, it says 

Error: 1 things prohibited this User from being saved:
 * Email already taken

It's ugly. Let's just display the errors instead of the whole message thing?

**Comment by guanhuay** [comment]
this problem can be solved by changing the file name devise.en.yml that is inside config/locale
and you search for the this line:         one: "1 error prohibited this %{resource} from being saved:"

change it to whatever you like!

**Comment by guanhuay** [comment]
and any other error display issue could be fixed the same way!
